### ISSUE TITLE
Directories still reference MonoBook

### ISSUE THREAD

**Issue by mostertb** [cforcomputer/Eveskin-for-Mediawiki#1]
Hi @cforcomputer 

Cool idea to recreate this skin.

I installed your `1.0` release in the `skins/Eveskin` directory (as per the instructions at https://www.mediawiki.org/wiki/Skin:Eveskin) to have a look and ran into the following naming issues:

1) You need to change the skin name  in `skins.json` to:
```json
"ValidSkinNames": {
	"eveskin": "MonoBook"
},
```
To be able to load it as `wfLoadSkin( 'eveskin' );`

2) The 'main.css' has several references to `/skins/MonoBook` when these should probably be `/skins/Eveskin`. These URLs also dont seem to work in my test deployment where MediaWiki is not installed in the wberoot

Keep up the good work. Cant wait to see a stable release

**Comment by cforcomputer** [comment]
Hi @mostertb 

I'm aware of this issue, I've tried changing every single reference to Monobook to eveskin, and it still wouldn't work. I'm almost absolutely sure that I didn't miss any. I was able to load the skin, but it would break the site when I tried to activate it.

The current fix to just replace the old MonoBook skin without any of the names being changed. Maybe I missed something basic like the json file, I'll take another look. If I remember correctly, the release I made did end up being partially broken, the source code should be stable if you rename the original MonoBook to MonoBook.old and bring in the new files, then load MonoBook.

Mediawiki is also installed webroot for me, so it might just be an underlying configuration error.
